param(
    [switch]$SplitExisting
)

$ErrorActionPreference = "Stop"

$sourceRoot = Join-Path $PSScriptRoot "src"
$aggregate = Join-Path $PSScriptRoot "csec_compiler.csec"

if (-not (Test-Path $sourceRoot)) {
    New-Item -ItemType Directory -Path $sourceRoot | Out-Null
}

function Write-TextFile {
    param(
        [string]$Path,
        [string]$Text
    )

    $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllText($Path, $Text, $utf8NoBom)
}

if ($SplitExisting) {
    if (-not (Test-Path $aggregate)) {
        Write-Error "Aggregate source not found: $aggregate"
    }

    $source = Get-Content $aggregate -Raw
    $parserMarker = "def validateBalanced(tokens: String): Boolean"
    $irMarker = "def parseReturnIntegerInRange(tokens: String, start: Int, end: Int): Int"
    $driverMarker = "def compileSource(source: String, mode: String): String"

    $parserStart = $source.IndexOf($parserMarker)
    $irStart = $source.IndexOf($irMarker)
    $driverStart = $source.IndexOf($driverMarker)

    if ($parserStart -lt 0 -or $irStart -lt 0 -or $driverStart -lt 0) {
        Write-Error "Failed to find selfhost split markers."
    }

    Write-TextFile (Join-Path $sourceRoot "lexer.csec") $source.Substring(0, $parserStart)
    Write-TextFile (Join-Path $sourceRoot "parser.csec") $source.Substring($parserStart, $irStart - $parserStart)
    Write-TextFile (Join-Path $sourceRoot "ir_generator.csec") $source.Substring($irStart, $driverStart - $irStart)
    Write-TextFile (Join-Path $sourceRoot "driver.csec") $source.Substring($driverStart)
}

$parts = @(
    "lexer.csec",
    "parser.csec",
    "ir_generator.csec",
    "driver.csec"
)

$output = "// Generated by selfhost/assemble_selfhost.ps1. Edit selfhost/src/*.csec instead.`n"
foreach ($part in $parts) {
    $path = Join-Path $sourceRoot $part
    if (-not (Test-Path $path)) {
        Write-Error "Missing selfhost source part: $path"
    }
    $text = Get-Content $path -Raw
    $output = $output + "`n// ---- selfhost/src/$part ----`n" + $text.TrimEnd() + "`n"
}

Write-TextFile $aggregate $output
Write-Host "Assembled $aggregate from selfhost/src/*.csec"
